# ---
# apiVersion: argoproj.io/v1alpha1
# kind: Application
# metadata:
#   name: nginx-ingress
#   namespace: argocd
# spec:
#   project: default
#   source:
#     repoURL: git@github.com:ququiz/argocd-k8s-ququiz.git
#     targetRevision: HEAD
#     path: ingress
#   destination:
#     server: https://kubernetes.default.svc
#     namespace: default
#   syncPolicy:
#     automated:
#       prune: true
#       selfHeal: true
#       allowEmpty: false
#     syncOptions:
#       - Validate=true
#       - CreateNamespace=true
#       - PrunePropagationPolicy=foreground
#       - PruneLast=true